base_output_dir: '/data/sguo/lif_split_npy/'
focal_plane_idx: 0
verbose: 10
split_volumes: True
splitter_class: LifStackSplitter2D
input_fname: '/home/sguo/LabData/DeviceData/CZLASX-01/Data/2018/LabelFree/04052018_LabelFree/20x20zstack_U2OS_DAPI_MitoTrackerRed_BF_Phase.lif'
correct_flat_field: True
flat_field_class: FlatFieldEstimator2D
use_masks: True
masks:
    mask_channels: [0, 1]
    str_elem_radius: 3
tile_stack: True
tile:
    channels: -1
    tile_size: [256, 256]
    step_size: [64, 64]
    save_cropped_masks: True
    min_fraction: 0.15
    hist_clip_limits: [2, 98]
