dataset:
    preprocess: False
    data_dir: '/data/processed_data/image_tile_256-256_step_256-256'
    input_channels: [3]
    target_channels: [4]
    split_by_column: sample_num
    split_ratio:
        train: 0.7
        val: 0.15
        test: 0.15
    height: 256
    width: 256
verbose: 10
trainer:
    model_dir: '/data/models/segm_tile256_bs16_mse_clr_nadam'
    batch_size: 16
    max_epochs: 50
    metrics: dice_coef
    loss: dice_coef_loss
    callbacks:
        LearningRateScheduler:
            lr_find: False
            base_lr: 0.001
            max_lr: 0.006
            step_size: 2
            gamma: 0.999
            scale_mode: iterations
        EarlyStopping:
            mode: min
            monitor: val_loss
            patience: 20
            verbose: True
        ModelCheckpoint:
            mode: min
            monitor: val_loss
            save_best_only: False
            verbose: True
        TensorBoard:
            histogram_freq: 0
            verbose: True
    optimizer:
        lr: 0.005
        name: Nadam
network:
    class: UNet2D
    num_input_channels: 1
    data_format: 'channels_first'
    height: 256
    width: 256
    batch_norm: True
    pooling_type: max
    filter_size: 3
    activation:
        type: relu
    dropout: 0.2
    num_filters_per_block: [16, 32, 64, 96, 128]
    num_convs_per_block: 2
    block_sequence: conv-activation-bn
    skip_merge_type: concat
    upsampling: bilinear
    residual: True
    num_target_channels: 1
    final_activation: sigmoid