dataset:
    preprocess: False
    data_dir: '/data/sguo/Processed/2018_07_03_KidneyTissueSection/SMS_2018_0703_1835_1_BG_2018_0703_1829_1/image_tile_256-256_step_64-64'
    input_channels: [5]
    target_channels: [5]
    split_by_column: sample_num
    split_ratio:
        train: 0.7
        val: 0.15
        test: 0.15
    height: 256
    width: 256
verbose: 10
trainer:
    model_dir: '/models_labelfree/tile256_step64_fltr8_128_lr1e-4_do0_mse_chan5_5_global_norm_no_batchnorm_augmented'
    batch_size: 64
    max_epochs: 200
    patience: 30
    metrics: coeff_determination
    loss: mean_squared_error
    augmentations: True
    callbacks:
        EarlyStopping:
            mode: min
            monitor: val_loss
            patience: 30
            verbose: True
        ModelCheckpoint:
            mode: min
            monitor: val_loss
            save_best_only: True
            verbose: True
        TensorBoard:
            histogram_freq: 0
            verbose: True
    optimizer:
        lr: 0.0001
        name: Adam
network:
    class: UNet2D
    num_filters_per_block: [8, 16, 32, 64, 128]
    num_convs_per_block: 2
    filter_size: 3
    batch_norm: False
    activation: relu
    pooling_type: average
    skip_merge_type: concat
    upsampling: bilinear
    dropout: 0
    residual: True
    height: 256
    width: 256
    num_input_channels: 1
    num_target_channels: 1
    data_format: 'channels_first'
    final_activation: linear
